- name: install and run nginix
  hosts: web
  become: yes #getting root access
  tasks: 
    - name: insall nginx
       ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start nginx
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes 
